---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "application.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  {{- with .Values.application }}
  {{- end }}
