---
name: "Clean deploy"
on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [closed]

permissions: {}

jobs:
  clean-deploy:
    uses: hoverkraft-tech/ci-github-publish/.github/workflows/clean-deploy.yml@84d583ba7b357f9476707f54cf5419d630ae0145 # 0.26.2
    permissions:
      actions: read
      deployments: write
      issues: write
      pull-requests: write
    with:
      clean-deploy-parameters: |
        { "repository": "${{ github.repository_owner}}/argocd-app-of-apps" }
      github-app-client-id: ${{ vars.CI_BOT_APP_CLIENT_ID }}
    secrets:
      github-app-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
